### ISSUE TITLE
Problemas com as texturas em componentes static

### ISSUE THREAD

**Issue by FilipeFCampos** [Aliragm/base_defense#16]
Não tô conseguindo adicionar texturas nem nas balas nem nos drops, ainda vou testar nos inimigos
Quando eu tento adicionar textura neles ou dá segmentation fault, ou a textura não aparece, ou nem compila e dá esse erro em anexo aí
Tentei declarar as texturas como static mas mesmo assim sem sucesso, deu erro de "std:bad_array_new_length"
Perdi a paciência e descartei as alterações, vou tentar fazer essa parte de novo quando tiver mais tempo, mas preciso de ajuda asap
Caso não tenha solução para as balas e drops, vou tentar pelo menos adicionar texturas nos inimigos e torcer para dar certo.
![image](https://github.com/user-attachments/assets/1a975f7e-f8e2-4853-a6ee-2e070a0a362b)
↑↑ Esse erro ocorreu quando eu tentei declarar as texturas como static, se alguém achar a solução para ele na internet eu agradeço.

**Comment by FilipeFCampos** [comment]
@Aliragm se prepare para a solução mais deselegante da história KKKKKKKKKKKKKKKKKKK

**Comment by Aliragm** [comment]
Qualquer coisa faz alocação dinâmica, confio em você.

**Comment by FilipeFCampos** [comment]
Consegui contornar o problema, todos as texturas foram adicionadas agora
