### ISSUE TITLE
Problema com o player.hpp

### ISSUE THREAD

**Issue by FilipeFCampos** [Aliragm/base_defense#18]
Tentei incluir o player.hpp no enemy.hpp. Não mudei NADA no header do player nem no cpp, o vscode também não deu nenhum aviso, mas na hora de compilar ele deu o erro a seguir:
![image](https://github.com/user-attachments/assets/aad21371-e74d-4ff6-bcaf-dd4e0f83e70a)
Dei ctrl-z e make clean e continuou dando a mesma coisa, tive que resetar todas as alterações que eu tinha feito desde o último commit para voltar a funcionar.
Após dar reset esse erro aí desapareceu mas eu consegui replicar ele de novo.
Ele não me impediu de implementar o que eu estava implementando (só tive que deixar ele quieto lá e usar outra abordagem para a feature que eu tava tentando programar), então no final deu certo, mas achei esse erro aí no mínimo peculiar, recomendo dar uma olhada e tomar cuidado.

**Comment by Aliragm** [comment]
Deve ser coisa do diabo.
