### ISSUE TITLE
Balas sumindo assim que o inimigo morre

### ISSUE THREAD

**Issue by FilipeFCampos** [Aliragm/base_defense#6]
Como as balas estão contidas em um vector dentro de cada inimigo, se o inimigo é destruído as balas são destruídas junto com ele.
A princípio a correção mais intuitiva para esse bug seria transformar o vector bullets em um static vector, mas quando eu tentei isso deu um erro de compilação gigante.
Requer solução, preciso de ajuda.

_To testando essas issues aqui, pode ser legal para ter em mente os componentes do projeto_

Valeu

**Comment by Aliragm** [comment]
Resolvi, declarei o vector de bullets como static e declarei o vetor fora de todas as funções de enemy.cpp e funcionou

vou criar uma branch e dar merge.
