### ISSUE TITLE
Inconsistência no comportamento das balas

### ISSUE THREAD

**Issue by FilipeFCampos** [Aliragm/base_defense#8]
As balas dos inimigos estão aumentando de velocidade a medida que o jogo roda sem explicação.
Assim que o jogo começa e um inimigo morre, as balas somem e reaparecem, o que também é estranho.
Não diria que a prioridade para resolver esse bug é muito alta mas deixarei registrado aqui.

https://github.com/user-attachments/assets/758ce2ba-993a-4768-bfd8-cb6b1fff83ff

**Comment by Aliragm** [comment]
Ia colocar essa issue agr kkkkkk

**Comment by FilipeFCampos** [comment]
Marco como wontfix?
